import { EventType } from '@/utils/types';
import { hoursPerPageOptions } from '@/utils/variables';
import { UUID } from 'server/types';

export interface SettingProviderProps {
  children: React.ReactNode;
}

/**
 * Typing for the settings state
 */
export interface SettingsContextType {
  settingsState: SettingsState;
  setSettingsState: React.Dispatch<React.SetStateAction<SettingsState>>;
  updateSettings: (newSettings: SettingsState) => void;
}

export const allBackgroundKeys = [
  'airi_1',
  'airi_2',
  'airi_3',
  'airi_4',
  'akito_1',
  'akito_2',
  'akito_3',
  'akito_4',
  'an_1',
  'an_2',
  'an_3',
  'an_4',
  'emu_1',
  'emu_2',
  'emu_3',
  'emu_4',
  'ena_1',
  'ena_2',
  'ena_3',
  'ena_4',
  'haruka_1',
  'haruka_2',
  'haruka_3',
  'haruka_4',
  'honami_1',
  'honami_2',
  'honami_3',
  'honami_4',
  'ichika_1',
  'ichika_2',
  'ichika_3',
  'ichika_4',
  'kaito_1',
  'kaito_2',
  'kaito_3',
  'kaito_4',
  'kanade_1',
  'kanade_2',
  'kanade_3',
  'kanade_4',
  'kohane_1',
  'kohane_2',
  'kohane_3',
  'kohane_4',
  'len_1',
  'len_2',
  'len_3',
  'len_4',
  'luka_1',
  'luka_2',
  'luka_3',
  'luka_4',
  'mafuyu_1',
  'mafuyu_2',
  'mafuyu_3',
  'mafuyu_4',
  'miku_1',
  'miku_2',
  'miku_3',
  'miku_4',
  'minori_1',
  'minori_2',
  'minori_3',
  'minori_4',
  'mizuki_1',
  'mizuki_2',
  'mizuki_3',
  'mizuki_4',
  'nene_1',
  'nene_2',
  'nene_3',
  'nene_4',
  'rin_1',
  'rin_2',
  'rin_3',
  'rin_4',
  'rui_1',
  'rui_2',
  'rui_3',
  'rui_4',
  'saki_1',
  'saki_2',
  'saki_3',
  'saki_4',
  'shiho_1',
  'shiho_2',
  'shiho_3',
  'shiho_4',
  'shizuku_1',
  'shizuku_2',
  'shizuku_3',
  'shizuku_4',
  'toya_1',
  'toya_2',
  'toya_3',
  'toya_4',
  'tsukasa_1',
  'tsukasa_2',
  'tsukasa_3',
  'tsukasa_4',
];

export const InitiateEvents: EventType[] = [
  {
    event_id: '00000000-0000-0000-0000-000000000000' as UUID,
    event_name: 'Loading...',
    event_type: 'C',
  },
];

export enum ECharacter {
  AIRI = 'airi',
  AKITO = 'akito',
  AN = 'an',
  EMU = 'emu',
  ENA = 'ena',
  HARUKA = 'haruka',
  HONAMI = 'honami',
  ICHIKA = 'ichika',
  KAITO = 'kaito',
  KANADE = 'kanade',
  KOHANE = 'kohane',
  LEN = 'len',
  LUKA = 'luka',
  MAFUYU = 'mafuyu',
  MIKU = 'miku',
  MINORI = 'minori',
  MIZUKI = 'mizuki',
  NENE = 'nene',
  RIN = 'rin',
  RUI = 'rui',
  SAKI = 'saki',
  SHIHO = 'shiho',
  SHIZUKU = 'shizuku',
  TOYA = 'toya',
  TSUKASA = 'tsukasa',
}

export const characterKeysMap: Record<ECharacter, string[]> = {
  [ECharacter.AIRI]: ['airi_1', 'airi_2', 'airi_3', 'airi_4'],
  [ECharacter.AKITO]: ['akito_1', 'akito_2', 'akito_3', 'akito_4'],
  [ECharacter.AN]: ['an_1', 'an_2', 'an_3', 'an_4'],
  [ECharacter.EMU]: ['emu_1', 'emu_2', 'emu_3', 'emu_4'],
  [ECharacter.ENA]: ['ena_1', 'ena_2', 'ena_3', 'ena_4'],
  [ECharacter.HARUKA]: ['haruka_1', 'haruka_2', 'haruka_3', 'haruka_4'],
  [ECharacter.HONAMI]: ['honami_1', 'honami_2', 'honami_3', 'honami_4'],
  [ECharacter.ICHIKA]: ['ichika_1', 'ichika_2', 'ichika_3', 'ichika_4'],
  [ECharacter.KAITO]: ['kaito_1', 'kaito_2', 'kaito_3', 'kaito_4'],
  [ECharacter.KANADE]: ['kanade_1', 'kanade_2', 'kanade_3', 'kanade_4'],
  [ECharacter.KOHANE]: ['kohane_1', 'kohane_2', 'kohane_3', 'kohane_4'],
  [ECharacter.LEN]: ['len_1', 'len_2', 'len_3', 'len_4'],
  [ECharacter.LUKA]: ['luka_1', 'luka_2', 'luka_3', 'luka_4'],
  [ECharacter.MAFUYU]: ['mafuyu_1', 'mafuyu_2', 'mafuyu_3', 'mafuyu_4'],
  [ECharacter.MIKU]: ['miku_1', 'miku_2', 'miku_3', 'miku_4'],
  [ECharacter.MINORI]: ['minori_1', 'minori_2', 'minori_3', 'minori_4'],
  [ECharacter.MIZUKI]: ['mizuki_1', 'mizuki_2', 'mizuki_3', 'mizuki_4'],
  [ECharacter.NENE]: ['nene_1', 'nene_2', 'nene_3', 'nene_4'],
  [ECharacter.RIN]: ['rin_1', 'rin_2', 'rin_3', 'rin_4'],
  [ECharacter.RUI]: ['rui_1', 'rui_2', 'rui_3', 'rui_4'],
  [ECharacter.SAKI]: ['saki_1', 'saki_2', 'saki_3', 'saki_4'],
  [ECharacter.SHIHO]: ['shiho_1', 'shiho_2', 'shiho_3', 'shiho_4'],
  [ECharacter.SHIZUKU]: ['shizuku_1', 'shizuku_2', 'shizuku_3', 'shizuku_4'],
  [ECharacter.TOYA]: ['toya_1', 'toya_2', 'toya_3', 'toya_4'],
  [ECharacter.TSUKASA]: ['tsukasa_1', 'tsukasa_2', 'tsukasa_3', 'tsukasa_4'],
};

export const DefaultSettings: SettingsState = {
  theme: EThemeNames.MIKU,
  favoriteCharacters: [],
  currentPageBackground: '',
  hoursPerPage: 10 as hoursPerPageOptions,
  startingHour: 1,
};

export type SettingsState = {
  theme: EThemeNames;
  favoriteCharacters: string[];
  currentPageBackground: string;
  hoursPerPage: hoursPerPageOptions;
  startingHour: number;
};

export const enum EThemeNames {
  TETO = 'teto',
  RIN = 'rin',
  LEN = 'len',
  GUMI = 'gumi',
  MIKU = 'miku',
  KAITO = 'kaito',
  LUKA = 'luka',
  GAKUPO = 'gakupo',
}

export const backgroundMap: Record<string, string> = {
  home: '/card-backgrounds/home.png',
  marathon: '/card-backgrounds/marathon.webp',
  carnival: '/card-backgrounds/carnival.png',
  about: '/card-backgrounds/about.jpg',
  createRun: '/card-backgrounds/create-run.webp',
  login: '/card-backgrounds/login.webp',
  register: '/card-backgrounds/register.webp',
  help: '/card-backgrounds/help.webp',
  authHelp: '/card-backgrounds/help.webp',
  data: '/card-backgrounds/data.webp',
  schedule: '/card-backgrounds/schedule.webp',
  settings: '/card-backgrounds/settings.webp',
  runData: '/card-backgrounds/run-data.webp',
  joinRun: '/card-backgrounds/join-run.webp',
  changeEvent: '/card-backgrounds/changeEvent.webp',
  airi_1: '/card-backgrounds/manager/airi_1.webp',
  airi_2: '/card-backgrounds/manager/airi_2.webp',
  airi_3: '/card-backgrounds/manager/airi_3.webp',
  airi_4: '/card-backgrounds/manager/airi_4.webp',
  akito_1: '/card-backgrounds/manager/akito_1.webp',
  akito_2: '/card-backgrounds/manager/akito_2.webp',
  akito_3: '/card-backgrounds/manager/akito_3.webp',
  akito_4: '/card-backgrounds/manager/akito_4.webp',
  an_1: '/card-backgrounds/manager/an_1.webp',
  an_2: '/card-backgrounds/manager/an_2.webp',
  an_3: '/card-backgrounds/manager/an_3.webp',
  an_4: '/card-backgrounds/manager/an_4.webp',
  emu_1: '/card-backgrounds/manager/emu_1.webp',
  emu_2: '/card-backgrounds/manager/emu_2.webp',
  emu_3: '/card-backgrounds/manager/emu_3.webp',
  emu_4: '/card-backgrounds/manager/emu_4.webp',
  ena_1: '/card-backgrounds/manager/ena_1.webp',
  ena_2: '/card-backgrounds/manager/ena_2.webp',
  ena_3: '/card-backgrounds/manager/ena_3.webp',
  ena_4: '/card-backgrounds/manager/ena_4.webp',
  haruka_1: '/card-backgrounds/manager/haruka_1.webp',
  haruka_2: '/card-backgrounds/manager/haruka_2.webp',
  haruka_3: '/card-backgrounds/manager/haruka_3.webp',
  haruka_4: '/card-backgrounds/manager/haruka_4.webp',
  honami_1: '/card-backgrounds/manager/honami_1.webp',
  honami_2: '/card-backgrounds/manager/honami_2.webp',
  honami_3: '/card-backgrounds/manager/honami_3.webp',
  honami_4: '/card-backgrounds/manager/honami_4.webp',
  ichika_1: '/card-backgrounds/manager/ichika_1.webp',
  ichika_2: '/card-backgrounds/manager/ichika_2.webp',
  ichika_3: '/card-backgrounds/manager/ichika_3.webp',
  ichika_4: '/card-backgrounds/manager/ichika_4.webp',
  kaito_1: '/card-backgrounds/manager/kaito_1.webp',
  kaito_2: '/card-backgrounds/manager/kaito_2.webp',
  kaito_3: '/card-backgrounds/manager/kaito_3.webp',
  kaito_4: '/card-backgrounds/manager/kaito_4.webp',
  kanade_1: '/card-backgrounds/manager/kanade_1.webp',
  kanade_2: '/card-backgrounds/manager/kanade_2.webp',
  kanade_3: '/card-backgrounds/manager/kanade_3.webp',
  kanade_4: '/card-backgrounds/manager/kanade_4.webp',
  kohane_1: '/card-backgrounds/manager/kohane_1.webp',
  kohane_2: '/card-backgrounds/manager/kohane_2.webp',
  kohane_3: '/card-backgrounds/manager/kohane_3.webp',
  kohane_4: '/card-backgrounds/manager/kohane_4.webp',
  len_1: '/card-backgrounds/manager/len_1.webp',
  len_2: '/card-backgrounds/manager/len_2.webp',
  len_3: '/card-backgrounds/manager/len_3.webp',
  len_4: '/card-backgrounds/manager/len_4.webp',
  luka_1: '/card-backgrounds/manager/luka_1.webp',
  luka_2: '/card-backgrounds/manager/luka_2.webp',
  luka_3: '/card-backgrounds/manager/luka_3.webp',
  luka_4: '/card-backgrounds/manager/luka_4.webp',
  mafuyu_1: '/card-backgrounds/manager/mafuyu_1.webp',
  mafuyu_2: '/card-backgrounds/manager/mafuyu_2.webp',
  mafuyu_3: '/card-backgrounds/manager/mafuyu_3.webp',
  mafuyu_4: '/card-backgrounds/manager/mafuyu_4.webp',
  miku_1: '/card-backgrounds/manager/miku_1.webp',
  miku_2: '/card-backgrounds/manager/miku_2.webp',
  miku_3: '/card-backgrounds/manager/miku_3.webp',
  miku_4: '/card-backgrounds/manager/miku_4.webp',
  minori_1: '/card-backgrounds/manager/minori_1.webp',
  minori_2: '/card-backgrounds/manager/minori_2.webp',
  minori_3: '/card-backgrounds/manager/minori_3.webp',
  minori_4: '/card-backgrounds/manager/minori_4.webp',
  mizuki_1: '/card-backgrounds/manager/mizuki_1.webp',
  mizuki_2: '/card-backgrounds/manager/mizuki_2.webp',
  mizuki_3: '/card-backgrounds/manager/mizuki_3.webp',
  mizuki_4: '/card-backgrounds/manager/mizuki_4.webp',
  nene_1: '/card-backgrounds/manager/nene_1.webp',
  nene_2: '/card-backgrounds/manager/nene_2.webp',
  nene_3: '/card-backgrounds/manager/nene_3.webp',
  nene_4: '/card-backgrounds/manager/nene_4.webp',
  rin_1: '/card-backgrounds/manager/rin_1.webp',
  rin_2: '/card-backgrounds/manager/rin_2.webp',
  rin_3: '/card-backgrounds/manager/rin_3.webp',
  rin_4: '/card-backgrounds/manager/rin_4.webp',
  rui_1: '/card-backgrounds/manager/rui_1.webp',
  rui_2: '/card-backgrounds/manager/rui_2.webp',
  rui_3: '/card-backgrounds/manager/rui_3.webp',
  rui_4: '/card-backgrounds/manager/rui_4.webp',
  saki_1: '/card-backgrounds/manager/saki_1.webp',
  saki_2: '/card-backgrounds/manager/saki_2.webp',
  saki_3: '/card-backgrounds/manager/saki_3.webp',
  saki_4: '/card-backgrounds/manager/saki_4.webp',
  shiho_1: '/card-backgrounds/manager/shiho_1.webp',
  shiho_2: '/card-backgrounds/manager/shiho_2.webp',
  shiho_3: '/card-backgrounds/manager/shiho_3.webp',
  shiho_4: '/card-backgrounds/manager/shiho_4.webp',
  shizuku_1: '/card-backgrounds/manager/shizuku_1.webp',
  shizuku_2: '/card-backgrounds/manager/shizuku_2.webp',
  shizuku_3: '/card-backgrounds/manager/shizuku_3.webp',
  shizuku_4: '/card-backgrounds/manager/shizuku_4.webp',
  toya_1: '/card-backgrounds/manager/toya_1.webp',
  toya_2: '/card-backgrounds/manager/toya_2.webp',
  toya_3: '/card-backgrounds/manager/toya_3.webp',
  toya_4: '/card-backgrounds/manager/toya_4.webp',
  tsukasa_1: '/card-backgrounds/manager/tsukasa_1.webp',
  tsukasa_2: '/card-backgrounds/manager/tsukasa_2.webp',
  tsukasa_3: '/card-backgrounds/manager/tsukasa_3.webp',
  tsukasa_4: '/card-backgrounds/manager/tsukasa_4.webp',
};
